---

- homebrew_tap:
  name: sanemat/font

- homebrew: name=ricty install_options=with-powerlie

- copy:
      src: /usr/local/opt/ricty/share/fonts/Ricty*.ttf
      dest: ~/Library/Fonts

- homebrew: name=fontforge state=latest upgrade_all=yes

- shell: fc-cache -vf
  environment:
      PATH: '/usr/local/bin:{{ ansible_env.PATH }}'
