---

- stat: path={{ ricty_install_dir }}/{{ item }}
  with_items:
    - '{{ target_fonts }}'
  register: ricty_fonts

- set_fact:
    is_install: False

- set_fact:
    is_install: True
  when: not {{ item.stat.exists }}
  with_items:
    - '{{ ricty_fonts.results }}'

- include: install.yml
  when: is_install == True
