---

- stat: path={{ ricty_install_dir }}/{{ item }}
  with_items:
    - Ricty-Regular.ttf
    - Ricty-Bold.ttf
    - RictyDiscord-Regular.ttf
    - RictyDiscord-Bold.ttf
  register: is_fonts

- set_fact:
    is_install: False

- set_fact:
    is_install: True
  when: not {{ item.stat.exists }}
  with_items:
    - '{{ is_fonts.results }}'

- include: install.yml
  when: is_install == True
