---

- name: Install macOS applications.
  homebrew_cask:
    name: "{{ item }}"
    state: present
    install_options: 'appdir=/Applications'
  with_items:
    - alfred
    - github
    - handbrake
    - iterm2
    - karabiner-elements
    - macs-fan-control
    - macvim
    - monolingual
    - qlmarkdown
    - vagrant
    - virtualbox
    - visual-studio-code
    - vlc
    - xld
    - zoomus

- name: Install mas-cli.
  homebrew:
    name: mas
    state: present
