---

- get_url:
    url: 'https://dl.bintray.com/mitchellh/vagrant/vagrant_{{ target_version }}.dmg'
    dest: '{{ download_dir }}'

- shell: 'hdiutil attach vagrant_{{ target_version }}.dmg'
  args:
    chdir: '{{ download_dir }}'

- shell: 'installer -pkg Vagrant.pkg -target /'
  args:
    chdir: '/Volumes/Vagrant'
    creates: '/usr/local/bin/vagrant'
  sudo: yes

- shell: 'hdiutil detach /Volumes/Vagrant'
  register: result
  until: result.rc == 0
  retries: 5
  delay: 3
