---

- stat: path=/usr/local/bin/brew
  register: brew_command

- shell: echo "\n" | ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  when: not brew_command.stat.exists

- shell: brew doctor
  environment:
    PATH: '/usr/local/bin:{{ ansible_env.PATH }}'

- homebrew: update_homebrew=yes upgrade_all=yes

- homebrew_tap:
    name: caskroom/cask
    state: present
