---

- shell: which /usr/local/bin/brew
  register: which_result

- shell: echo "\n" | ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  when: which_result.rc == 1

- shell: /usr/local/bin/brew update
