---

- homebrew: name=python state=latest upgrade_all=yes install_options=framework

- shell: 'easy_install pip'
  sudo: yes

- pip: name={{ item }}
  with_items:
    - virtualenv
  environment:
    PATH: '/usr/local/bin:{{ ansible_env.PATH }}'
  sudo: yes

- pip: name=virtualenvwrapper extra_args='--ignore-installed six'
  environment:
    PATH: '/usr/local/bin:{{ ansible_env.PATH }}'
  sudo: yes
