---
# TODO: install color theme

- get_url:
    url=https://iterm2.com/downloads/stable/iTerm2-{{ item2_version }}.zip
    dest={{ user_downloads_dir }}

- shell: 'unzip {{ user_downloads_dir }}/iTerm2-{{ item2_version }}.zip'
  args:
    chdir: '{{ user_downloads_dir }}'
    creates: '{{ user_downloads_dir }}/iTerm.app'

- shell: 'mv {{ user_downloads_dir }}/iTerm.app {{ root_applications_dir }}'
  args:
    chdir: '{{ user_downloads_dir }}'
    creates: '{{ root_applications_dir }}/iTerm.app'

- homebrew: name={{ item }} state=latest upgrade_all=yes
  with_items:
    - zsh
    - tmux
    - peco

- git: repo={{ item.url }} dest={{ item.dest }}
  with_items:
    - { url: 'https://github.com/robbyrussell/oh-my-zsh.git', dest: '~/.oh-my-zsh' }
    - { url: 'https://github.com/sbkro/dotfiles.git', dest: '~/.dotfiles' }

- file: src=~/.dotfiles/{{ item.path }} dest={{ item.dest }} state=link
  with_items:
    - { path: zsh/_zshrc, dest: ~/.zshrc }
    - { path: tmux/_tmux.conf, dest: ~/.tmux.conf }
    - { path: readline/_inputrc, dest: ~/.inputrc }
