---

- homebrew_tap: tap=caskroom/versions state=present

- homebrew_cask: name=parallels10 state=present
  environment:
    HOMEBREW_CASK_OPTS: '{{ homebrew_cask_opts }}'

- shell: which /usr/local/bin/vagrant
  register: vagrant_path

- shell: vagrant plugin install vagrant-parallels
  environment:
    PATH: '/usr/local/bin:{{ ansible_env.PATH }}'
  when: vagrant_path != ""
